In [1]:
import pandas as pd

In [128]:
datos = pd.read_csv('datos_abiertos_covid19/211213COVID19MEXICO.csv')

/home/gomosak/ds/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (38) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [129]:
datos.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2021-12-13,z3be8c,2,12,7,1,7,7,101,1,...,2,1,2,2,97,7,99,México,97,97
1,2021-12-13,z526b3,2,12,9,1,9,9,12,1,...,1,2,97,1,1,3,99,México,97,97
2,2021-12-13,z3d1e2,2,12,9,1,9,9,5,1,...,1,1,1,2,97,3,99,México,97,97
3,2021-12-13,z17f15,1,12,7,1,7,7,101,1,...,2,2,97,2,97,6,99,México,97,97
4,2021-12-13,z21f6f,2,12,7,1,7,7,9,1,...,2,1,1,2,97,3,99,México,97,97

In [130]:
datos.shape

(12074161, 40)

In [131]:
a = datos.iloc[0];a

FECHA_ACTUALIZACION      2021-12-13
ID_REGISTRO                  z3be8c
ORIGEN                            2
SECTOR                           12
ENTIDAD_UM                        7
SEXO                              1
ENTIDAD_NAC                       7
ENTIDAD_RES                       7
MUNICIPIO_RES                   101
TIPO_PACIENTE                     1
FECHA_INGRESO            2020-08-18
FECHA_SINTOMAS           2020-08-14
FECHA_DEF                9999-99-99
INTUBADO                         97
NEUMONIA                          2
EDAD                             40
NACIONALIDAD                      1
EMBARAZO                          2
HABLA_LENGUA_INDIG                2
INDIGENA                          2
DIABETES                          2
EPOC                              2
ASMA                              2
INMUSUPR                          2
HIPERTENSION                      2
OTRA_COM                          2
CARDIOVASCULAR                    2
OBESIDAD                          2
RENAL_CRONICA                     2
TABAQUISMO                        2
OTRO_CASO                         2
TOMA_MUESTRA_LAB                  1
RESULTADO_LAB                     2
TOMA_MUESTRA_ANTIGENO             2
RESULTADO_ANTIGENO               97
CLASIFICACION_FINAL               7
MIGRANTE                         99
PAIS_NACIONALIDAD            México
PAIS_ORIGEN                      97
UCI                              97
Name: 0, dtype: object

In [239]:
Morelia = datos

In [240]:
Morelia.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2021-12-13,z3be8c,2,12,7,1,7,7,101,1,...,2,1,2,2,97,7,99,México,97,97
1,2021-12-13,z526b3,2,12,9,1,9,9,12,1,...,1,2,97,1,1,3,99,México,97,97
2,2021-12-13,z3d1e2,2,12,9,1,9,9,5,1,...,1,1,1,2,97,3,99,México,97,97
3,2021-12-13,z17f15,1,12,7,1,7,7,101,1,...,2,2,97,2,97,6,99,México,97,97
4,2021-12-13,z21f6f,2,12,7,1,7,7,9,1,...,2,1,1,2,97,3,99,México,97,97

In [241]:
Morelia = Morelia[(Morelia.ENTIDAD_UM == 16)]

Morelia

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
85,2021-12-13,zz7202,1,12,16,2,16,16,112,1,...,1,1,2,2,97,7,99,México,97,97
199,2021-12-13,1442fd,1,4,16,1,16,16,53,2,...,99,1,2,2,97,7,99,México,97,99
382,2021-12-13,1d50dc,1,4,16,1,12,16,52,2,...,99,1,2,2,97,7,99,México,97,99
401,2021-12-13,1e005b,1,4,16,1,16,16,52,1,...,99,2,97,2,97,6,99,México,97,97
429,2021-12-13,054314,1,4,16,2,16,16,52,1,...,99,2,97,2,97,6,99,México,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12042768,2021-12-13,99b406,2,12,16,1,16,16,55,1,...,2,2,97,1,2,7,99,México,97,97
12043135,2021-12-13,d231f1,1,12,16,2,16,16,73,1,...,2,2,97,1,2,7,99,México,97,97
12043217,2021-12-13,bd15da,2,4,16,1,16,16,6,1,...,2,2,97,1,2,7,99,México,97,97
12043220,2021-12-13,922235,1,12,16,1,16,16,66,1,...,2,2,97,1,2,7,99,México,97,97
12043312,2021-12-13,6793ff,2,4,16,2,16,16,6,1,...,2,2,97,1,2,7,99,México,97,97

In [242]:
Morelia = Morelia[(Morelia.MUNICIPIO_RES == 52)]
Morelia

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
382,2021-12-13,1d50dc,1,4,16,1,12,16,52,2,...,99,1,2,2,97,7,99,México,97,99
401,2021-12-13,1e005b,1,4,16,1,16,16,52,1,...,99,2,97,2,97,6,99,México,97,97
429,2021-12-13,054314,1,4,16,2,16,16,52,1,...,99,2,97,2,97,6,99,México,97,97
432,2021-12-13,1a18dc,1,4,16,2,16,16,52,2,...,99,1,2,2,97,7,99,México,97,99
1074,2021-12-13,17c34a,1,4,16,2,16,16,52,2,...,99,1,2,2,97,7,99,México,97,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12041162,2021-12-13,75ada1,1,12,16,1,16,16,52,1,...,2,2,97,1,2,7,99,México,97,97
12041214,2021-12-13,9a23e9,1,12,16,1,16,16,52,1,...,2,2,97,1,2,7,99,México,97,97
12041706,2021-12-13,93faa2,1,12,16,1,12,16,52,1,...,2,2,97,1,2,7,99,México,97,97
12041780,2021-12-13,534bf7,1,12,16,1,16,16,52,1,...,2,2,97,1,2,7,99,México,97,97
12042007,2021-12-13,74052a,1,12,16,1,16,16,52,1,...,2,2,97,1,2,7,99,México,97,97

In [243]:
columnas = ['FECHA_ACTUALIZACION','ID_REGISTRO','ORIGEN','ENTIDAD_RES','MUNICIPIO_RES','INTUBADO'
,'NEUMONIA','EDAD','DIABETES','ASMA','HIPERTENSION','OBESIDAD','TABAQUISMO','TOMA_MUESTRA_LAB','RESULTADO_ANTIGENO']

In [244]:
Morelia.shape

(32079, 40)

In [245]:
Morelia.loc[:,['FECHA_ACTUALIZACION','ID_REGISTRO','ORIGEN','ENTIDAD_RES','MUNICIPIO_RES','INTUBADO'
,'NEUMONIA','EDAD','DIABETES','ASMA','HIPERTENSION','OBESIDAD','TABAQUISMO','TOMA_MUESTRA_LAB','RESULTADO_ANTIGENO']]

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,ENTIDAD_RES,MUNICIPIO_RES,INTUBADO,NEUMONIA,EDAD,DIABETES,ASMA,HIPERTENSION,OBESIDAD,TABAQUISMO,TOMA_MUESTRA_LAB,RESULTADO_ANTIGENO
382,2021-12-13,1d50dc,1,16,52,99,99,68,1,2,1,2,2,1,97
401,2021-12-13,1e005b,1,16,52,97,99,76,2,2,2,2,2,2,97
429,2021-12-13,054314,1,16,52,97,99,25,2,2,2,2,2,2,97
432,2021-12-13,1a18dc,1,16,52,99,99,76,2,2,2,2,2,1,97
1074,2021-12-13,17c34a,1,16,52,99,99,1,2,2,2,2,2,1,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12041162,2021-12-13,75ada1,1,16,52,97,2,23,2,2,2,2,2,2,2
12041214,2021-12-13,9a23e9,1,16,52,97,2,23,2,2,2,2,2,2,2
12041706,2021-12-13,93faa2,1,16,52,97,2,36,2,2,2,2,2,2,2
12041780,2021-12-13,534bf7,1,16,52,97,2,21,2,2,2,2,2,2,2
12042007,2021-12-13,74052a,1,16,52,97,2,18,2,2,2,2,2,2,2

In [246]:
Morelia = Morelia.loc[:,['FECHA_ACTUALIZACION','ID_REGISTRO'
,'ORIGEN'
,'SECTOR'
,'ENTIDAD_RES'
,'SEXO'
,'MUNICIPIO_RES'
,'INTUBADO'
,'FECHA_DEF'
,'NEUMONIA'
,'EDAD'
,'DIABETES'
,'ASMA'
,'HIPERTENSION'
,'OBESIDAD'
,'TABAQUISMO'
,'TOMA_MUESTRA_LAB'
,'CLASIFICACION_FINAL' 
,'RESULTADO_LAB'
,'UCI']]

In [247]:
Morelia.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,NEUMONIA,EDAD,DIABETES,ASMA,HIPERTENSION,OBESIDAD,TABAQUISMO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
382,2021-12-13,1d50dc,1,4,16,1,52,99,2020-01-24,99,68,1,2,1,2,2,1,7,2,99
401,2021-12-13,1e005b,1,4,16,1,52,97,9999-99-99,99,76,2,2,2,2,2,2,6,97,97
429,2021-12-13,054314,1,4,16,2,52,97,9999-99-99,99,25,2,2,2,2,2,2,6,97,97
432,2021-12-13,1a18dc,1,4,16,2,52,99,9999-99-99,99,76,2,2,2,2,2,1,7,2,99
1074,2021-12-13,17c34a,1,4,16,2,52,99,9999-99-99,99,1,2,2,2,2,2,1,7,2,99

In [248]:
Morelia['FECHA_ACTUALIZACION'].unique()

array(['2021-12-13'], dtype=object)

In [249]:
Morelia_Muertos = Morelia[(Morelia.FECHA_DEF != '9999-99-99') & ((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3))]
Morelia_MuertosN = Morelia_Muertos.shape[0]
Morelia_Muertos

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,NEUMONIA,EDAD,DIABETES,ASMA,HIPERTENSION,OBESIDAD,TABAQUISMO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
42078,2021-12-13,19fea6,1,12,16,2,52,1,2020-03-26,1,72,1,2,2,1,2,1,3,1,1
42270,2021-12-13,0863b9,1,12,16,1,52,2,2020-04-13,1,63,2,2,2,1,2,1,3,1,2
49136,2021-12-13,129268,1,12,16,2,52,2,2020-04-25,1,69,2,2,2,2,2,1,3,1,2
56684,2021-12-13,020054,1,4,16,2,52,2,2020-04-26,1,74,2,2,1,1,2,1,3,1,2
67319,2021-12-13,19076f,1,4,16,2,52,2,2020-04-19,1,71,1,2,2,2,1,1,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10803757,2021-12-13,a42064,1,12,16,2,52,2,2021-10-08,1,69,2,2,1,2,2,1,3,1,2
10918691,2021-12-13,d3d91e,1,4,16,2,52,2,2021-10-15,1,51,2,2,2,1,2,1,3,1,2
10976848,2021-12-13,d7ba23,1,4,16,2,52,2,2021-10-15,1,58,2,2,2,2,1,1,3,1,2
11447815,2021-12-13,85b16e,1,12,16,1,52,2,2021-11-12,1,45,2,2,2,2,2,1,3,1,2
11678664,2021-12-13,975191,1,4,16,2,52,2,2021-12-05,1,72,2,2,2,2,2,1,3,1,2

In [250]:
Morelia_infectados = Morelia[((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3))]
Morelia_infectados_N = Morelia_infectados.shape[0]
Morelia_infectados_N
Morelia_infectados

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,NEUMONIA,EDAD,DIABETES,ASMA,HIPERTENSION,OBESIDAD,TABAQUISMO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
31176,2021-12-13,18ef9f,1,4,16,1,52,97,9999-99-99,2,20,2,2,2,2,2,1,3,1,97
42078,2021-12-13,19fea6,1,12,16,2,52,1,2020-03-26,1,72,1,2,2,1,2,1,3,1,1
42270,2021-12-13,0863b9,1,12,16,1,52,2,2020-04-13,1,63,2,2,2,1,2,1,3,1,2
42371,2021-12-13,1c613d,2,12,16,1,52,97,9999-99-99,1,29,2,2,2,2,2,1,3,1,97
42382,2021-12-13,0d8077,2,12,16,2,52,97,9999-99-99,2,31,2,2,2,2,2,1,3,1,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11945618,2021-12-13,9330e9,1,4,16,2,52,97,9999-99-99,2,24,2,2,2,2,2,1,3,1,97
11945697,2021-12-13,984fc9,1,4,16,1,52,97,9999-99-99,2,26,2,2,2,2,2,1,3,1,97
11977561,2021-12-13,c89829,2,12,16,2,52,97,9999-99-99,2,39,2,2,2,2,2,1,3,1,97
11977949,2021-12-13,83bbe0,2,12,16,2,52,97,9999-99-99,2,58,2,2,2,2,2,1,3,1,97
11984735,2021-12-13,910b87,2,6,16,2,52,97,9999-99-99,2,43,2,2,2,1,2,2,3,97,97

In [251]:
Morelia_infectadosG_vivos = Morelia[(Morelia.FECHA_DEF == '9999-99-99') & ((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3)) & (Morelia.INTUBADO == 1)]

Morelia_infectadosG_vivos_N = Morelia_infectadosG_vivos.shape[0]

Morelia_infectados_graves

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,NEUMONIA,EDAD,DIABETES,ASMA,HIPERTENSION,OBESIDAD,TABAQUISMO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,UCI
223860,2021-12-13,1a50c9,2,9,16,1,52,1,9999-99-99,2,55,1,2,2,2,2,1,3,1
233500,2021-12-13,0a8210,2,9,16,2,52,1,9999-99-99,2,65,1,2,2,2,2,1,3,2
328407,2021-12-13,0594b3,2,4,16,2,52,1,9999-99-99,1,38,2,2,2,2,2,1,3,2
423169,2021-12-13,0635fc,1,4,16,2,52,1,9999-99-99,1,31,2,2,2,2,2,1,3,2
437110,2021-12-13,12de0e,1,4,16,2,52,1,9999-99-99,1,67,2,2,2,2,2,1,3,2
498284,2021-12-13,1936e4,1,4,16,2,52,1,9999-99-99,1,41,2,2,2,2,2,1,3,2
508925,2021-12-13,1462bc,1,4,16,2,52,1,9999-99-99,2,38,2,2,1,1,2,1,3,2
645907,2021-12-13,14efdd,1,4,16,2,52,1,9999-99-99,2,64,1,2,2,2,1,1,3,2
705583,2021-12-13,17df54,1,4,16,2,52,1,9999-99-99,1,53,2,2,2,2,2,1,3,2
990125,2021-12-13,0477cc,1,4,16,2,52,1,9999-99-99,1,55,2,2,2,2,2,1,3,2
1008342,2021-12-13,141f18,1,4,16,2,52,1,9999-99-99,2,52,2,2,2,2,2,1,3,2
3411562,2021-12-13,38e03e,2,11,16,2,52,1,9999-99-99,1,79,2,2,1,2,2,1,3,2
4711933,2021-12-13,68a2ab,2,6,16,1,52,1,9999-99-99,1,56,2,2,2,1,2,1,3,2
6419433,2021-12-13,683cba,1,12,16,2,52,1,9999-99-99,1,50,1,2,1,1,2,1,3,2
8810689,2021-12-13,663e37,1,12,16,2,52,1,9999-99-99,1,62,2,2,1,2,2,1,3,1
9869524,2021-12-13,68615c,1,12,16,1,52,1,9999-99-99,1,17,2,2,2,1,2,1,3,2
10070245,2021-12-13,8d7522,2,9,16,1,52,1,9999-99-99,1,47,98,98,98,98,98,2,1,1

In [252]:
Morelia_infectados_grave = Morelia[((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3)) & (Morelia.INTUBADO == 1)]

Morelia_infectados_grave_N = Morelia_infectados_grave.shape[0]

Morelia_infectados_grave

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,NEUMONIA,EDAD,DIABETES,ASMA,HIPERTENSION,OBESIDAD,TABAQUISMO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
42078,2021-12-13,19fea6,1,12,16,2,52,1,2020-03-26,1,72,1,2,2,1,2,1,3,1,1
75337,2021-12-13,0dde42,2,6,16,2,52,1,2020-04-25,1,43,2,2,2,1,2,1,3,1,1
100967,2021-12-13,12a794,1,4,16,2,52,1,2020-05-05,1,75,2,2,2,2,2,1,3,1,2
115506,2021-12-13,1b09dc,1,4,16,2,52,1,2020-04-28,1,71,2,2,1,2,2,1,3,1,2
135807,2021-12-13,0fdf7d,1,12,16,2,52,1,2020-05-01,1,52,2,2,2,2,2,1,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9869524,2021-12-13,68615c,1,12,16,1,52,1,9999-99-99,1,17,2,2,2,1,2,1,3,1,2
10014525,2021-12-13,c55a52,1,4,16,1,52,1,2021-09-09,1,64,1,2,1,2,2,1,3,1,2
10070245,2021-12-13,8d7522,2,9,16,1,52,1,9999-99-99,1,47,98,98,98,98,98,2,1,97,1
10206098,2021-12-13,ba0a89,2,6,16,1,52,1,2021-10-01,1,79,2,1,2,1,2,2,3,97,2
10559954,2021-12-13,4ee4cb,1,4,16,2,52,1,2021-10-07,1,72,1,2,1,2,2,1,3,1,2

In [253]:
Morelia_infectadosG_Muertos = Morelia[(Morelia.FECHA_DEF != '9999-99-99') & ((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3)) & (Morelia.INTUBADO == 1)]
Morelia_infectadosG_MuertosN = Morelia_infectadosG_Muertos.shape[0]

# ((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3))
Morelia_infectadosG_Muertos

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,NEUMONIA,EDAD,DIABETES,ASMA,HIPERTENSION,OBESIDAD,TABAQUISMO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
42078,2021-12-13,19fea6,1,12,16,2,52,1,2020-03-26,1,72,1,2,2,1,2,1,3,1,1
75337,2021-12-13,0dde42,2,6,16,2,52,1,2020-04-25,1,43,2,2,2,1,2,1,3,1,1
100967,2021-12-13,12a794,1,4,16,2,52,1,2020-05-05,1,75,2,2,2,2,2,1,3,1,2
115506,2021-12-13,1b09dc,1,4,16,2,52,1,2020-04-28,1,71,2,2,1,2,2,1,3,1,2
135807,2021-12-13,0fdf7d,1,12,16,2,52,1,2020-05-01,1,52,2,2,2,2,2,1,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9734475,2021-12-13,488b3f,1,12,16,1,52,1,2021-09-10,1,64,1,2,1,1,2,1,3,1,2
9795703,2021-12-13,d1b72c,2,4,16,2,52,1,2021-09-06,1,76,1,2,1,2,1,1,3,1,2
10014525,2021-12-13,c55a52,1,4,16,1,52,1,2021-09-09,1,64,1,2,1,2,2,1,3,1,2
10206098,2021-12-13,ba0a89,2,6,16,1,52,1,2021-10-01,1,79,2,1,2,1,2,2,3,97,2
10559954,2021-12-13,4ee4cb,1,4,16,2,52,1,2021-10-07,1,72,1,2,1,2,2,1,3,1,2

In [254]:
Morelia_infectadosG = Morelia[ (Morelia.RESULTADO_LAB == 1 )
                                    & (Morelia.INTUBADO == 1)]


Morelia_infectadosGN = Morelia_infectadosG.shape[0]
Morelia_infectadosG

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,NEUMONIA,EDAD,DIABETES,ASMA,HIPERTENSION,OBESIDAD,TABAQUISMO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
42078,2021-12-13,19fea6,1,12,16,2,52,1,2020-03-26,1,72,1,2,2,1,2,1,3,1,1
75337,2021-12-13,0dde42,2,6,16,2,52,1,2020-04-25,1,43,2,2,2,1,2,1,3,1,1
100967,2021-12-13,12a794,1,4,16,2,52,1,2020-05-05,1,75,2,2,2,2,2,1,3,1,2
115506,2021-12-13,1b09dc,1,4,16,2,52,1,2020-04-28,1,71,2,2,1,2,2,1,3,1,2
135807,2021-12-13,0fdf7d,1,12,16,2,52,1,2020-05-01,1,52,2,2,2,2,2,1,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9734475,2021-12-13,488b3f,1,12,16,1,52,1,2021-09-10,1,64,1,2,1,1,2,1,3,1,2
9795703,2021-12-13,d1b72c,2,4,16,2,52,1,2021-09-06,1,76,1,2,1,2,1,1,3,1,2
9869524,2021-12-13,68615c,1,12,16,1,52,1,9999-99-99,1,17,2,2,2,1,2,1,3,1,2
10014525,2021-12-13,c55a52,1,4,16,1,52,1,2021-09-09,1,64,1,2,1,2,2,1,3,1,2
10559954,2021-12-13,4ee4cb,1,4,16,2,52,1,2021-10-07,1,72,1,2,1,2,2,1,3,1,2

In [255]:
Morelia_negativos =  Morelia[ (Morelia.RESULTADO_LAB == 2 )]
Morelia_negativosN = Morelia_negativos.shape[0]
Morelia_negativos

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,NEUMONIA,EDAD,DIABETES,ASMA,HIPERTENSION,OBESIDAD,TABAQUISMO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
382,2021-12-13,1d50dc,1,4,16,1,52,99,2020-01-24,99,68,1,2,1,2,2,1,7,2,99
432,2021-12-13,1a18dc,1,4,16,2,52,99,9999-99-99,99,76,2,2,2,2,2,1,7,2,99
1074,2021-12-13,17c34a,1,4,16,2,52,99,9999-99-99,99,1,2,2,2,2,2,1,7,2,99
1075,2021-12-13,1b3a24,1,4,16,1,52,99,9999-99-99,99,77,1,2,1,2,2,1,7,2,99
1362,2021-12-13,0f362b,1,4,16,1,52,99,9999-99-99,99,5,2,2,2,2,2,1,7,2,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11928470,2021-12-13,9870b7,1,4,16,2,52,2,9999-99-99,2,69,2,2,2,2,2,1,7,2,2
11931874,2021-12-13,5d2d7f,2,12,16,2,52,97,9999-99-99,2,38,2,2,2,2,2,1,7,2,97
11935331,2021-12-13,77f447,1,12,16,2,52,97,9999-99-99,2,16,2,2,2,2,2,1,7,2,97
11975860,2021-12-13,599297,2,12,16,2,52,97,9999-99-99,2,47,2,2,1,2,2,1,7,2,97
11993032,2021-12-13,caa175,1,4,16,1,52,2,9999-99-99,1,77,1,2,1,2,2,1,7,2,2

In [256]:
datos_finales = [Morelia_MuertosN
,Morelia_infectados_N
,Morelia_infectadosG_vivos_N 
,Morelia_infectadosG_MuertosN
,Morelia_infectados_grave_N
,Morelia.shape[0]];datos_finales
#,Morelia_MuertosN+Morelia_infectados_N+Morelia_infectadosG_vivos_N +Morelia_infectadosG_MuertosN];datos_f

[668, 11890, 17, 136, 153, 32079]

In [257]:
rows = ['Muertos','Infectados','Infectados graves vivos','Infectados graves muertos','Infectados graves','Total']
col = ['Casos']
df = pd.DataFrame(data = datos_finales, columns = col, index = rows)
df

                           Casos
Muertos                      668
Infectados                 11890
Infectados graves vivos       17
Infectados graves muertos    136
Infectados graves            153
Total                      32079

In [262]:
#total = Morelia_MuertosN+Morelia_infectados_N+Morelia_infectadosG_vivos_N +Morelia_infectadosG_MuertosN

total = Morelia.shape[0]
porce = [(Morelia_MuertosN*100)/total,(Morelia_infectados_N*100)/total,(Morelia_infectadosG_vivos_N*100)/total,(Morelia_infectadosG_MuertosN*100)/total,(Morelia_infectados_grave_N*100)/total,100]
porce

[2.0823591757847812,
 37.06474640730696,
 0.052994170641229466,
 0.4239533651298357,
 0.4769475357710652,
 100]

In [263]:
df['Porcentaje'] = porce
df

                           Casos  Porcentaje
Muertos                      668    2.082359
Infectados                 11890   37.064746
Infectados graves vivos       17    0.052994
Infectados graves muertos    136    0.423953
Infectados graves            153    0.476948
Total                      32079  100.000000

In [ ]:
df1

In [267]:
pM = 136*100/153
pig = 153*100/11890

In [268]:
pM

88.88888888888889

In [266]:
pig

1.2867956265769553

In [277]:
df1 = pd.DataFrame(data = [pM,pig], index = ('Infectados graves muertos','Infectados'), columns = ['Porcentaje'] )
df1

                           Porcentaje
Infectados graves muertos   88.888889
Infectados                   1.286796