In [1]:
import pandas as pd

In [2]:
datos = pd.read_csv('datos_abiertos_covid19/211213COVID19MEXICO.csv')

/home/gomosak/ds/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (38) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
datos.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2021-12-13,z3be8c,2,12,7,1,7,7,101,1,...,2,1,2,2,97,7,99,México,97,97
1,2021-12-13,z526b3,2,12,9,1,9,9,12,1,...,1,2,97,1,1,3,99,México,97,97
2,2021-12-13,z3d1e2,2,12,9,1,9,9,5,1,...,1,1,1,2,97,3,99,México,97,97
3,2021-12-13,z17f15,1,12,7,1,7,7,101,1,...,2,2,97,2,97,6,99,México,97,97
4,2021-12-13,z21f6f,2,12,7,1,7,7,9,1,...,2,1,1,2,97,3,99,México,97,97

In [4]:
datos.shape

(12074161, 40)

In [5]:
a = datos.iloc[0];a

FECHA_ACTUALIZACION      2021-12-13
ID_REGISTRO                  z3be8c
ORIGEN                            2
SECTOR                           12
ENTIDAD_UM                        7
SEXO                              1
ENTIDAD_NAC                       7
ENTIDAD_RES                       7
MUNICIPIO_RES                   101
TIPO_PACIENTE                     1
FECHA_INGRESO            2020-08-18
FECHA_SINTOMAS           2020-08-14
FECHA_DEF                9999-99-99
INTUBADO                         97
NEUMONIA                          2
EDAD                             40
NACIONALIDAD                      1
EMBARAZO                          2
HABLA_LENGUA_INDIG                2
INDIGENA                          2
DIABETES                          2
EPOC                              2
ASMA                              2
INMUSUPR                          2
HIPERTENSION                      2
OTRA_COM                          2
CARDIOVASCULAR                    2
OBESIDAD                          2
RENAL_CRONICA                     2
TABAQUISMO                        2
OTRO_CASO                         2
TOMA_MUESTRA_LAB                  1
RESULTADO_LAB                     2
TOMA_MUESTRA_ANTIGENO             2
RESULTADO_ANTIGENO               97
CLASIFICACION_FINAL               7
MIGRANTE                         99
PAIS_NACIONALIDAD            México
PAIS_ORIGEN                      97
UCI                              97
Name: 0, dtype: object

In [95]:
Morelia = datos

In [96]:
Morelia.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
0,2021-12-13,z3be8c,2,12,7,1,7,7,101,1,...,2,1,2,2,97,7,99,México,97,97
1,2021-12-13,z526b3,2,12,9,1,9,9,12,1,...,1,2,97,1,1,3,99,México,97,97
2,2021-12-13,z3d1e2,2,12,9,1,9,9,5,1,...,1,1,1,2,97,3,99,México,97,97
3,2021-12-13,z17f15,1,12,7,1,7,7,101,1,...,2,2,97,2,97,6,99,México,97,97
4,2021-12-13,z21f6f,2,12,7,1,7,7,9,1,...,2,1,1,2,97,3,99,México,97,97

In [97]:
Morelia = Morelia[(Morelia.ENTIDAD_UM == 16)]

Morelia

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
85,2021-12-13,zz7202,1,12,16,2,16,16,112,1,...,1,1,2,2,97,7,99,México,97,97
199,2021-12-13,1442fd,1,4,16,1,16,16,53,2,...,99,1,2,2,97,7,99,México,97,99
382,2021-12-13,1d50dc,1,4,16,1,12,16,52,2,...,99,1,2,2,97,7,99,México,97,99
401,2021-12-13,1e005b,1,4,16,1,16,16,52,1,...,99,2,97,2,97,6,99,México,97,97
429,2021-12-13,054314,1,4,16,2,16,16,52,1,...,99,2,97,2,97,6,99,México,97,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12042768,2021-12-13,99b406,2,12,16,1,16,16,55,1,...,2,2,97,1,2,7,99,México,97,97
12043135,2021-12-13,d231f1,1,12,16,2,16,16,73,1,...,2,2,97,1,2,7,99,México,97,97
12043217,2021-12-13,bd15da,2,4,16,1,16,16,6,1,...,2,2,97,1,2,7,99,México,97,97
12043220,2021-12-13,922235,1,12,16,1,16,16,66,1,...,2,2,97,1,2,7,99,México,97,97
12043312,2021-12-13,6793ff,2,4,16,2,16,16,6,1,...,2,2,97,1,2,7,99,México,97,97

In [98]:
Morelia = Morelia[(Morelia.MUNICIPIO_RES == 52)]
Morelia

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,OTRO_CASO,TOMA_MUESTRA_LAB,RESULTADO_LAB,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,CLASIFICACION_FINAL,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
382,2021-12-13,1d50dc,1,4,16,1,12,16,52,2,...,99,1,2,2,97,7,99,México,97,99
401,2021-12-13,1e005b,1,4,16,1,16,16,52,1,...,99,2,97,2,97,6,99,México,97,97
429,2021-12-13,054314,1,4,16,2,16,16,52,1,...,99,2,97,2,97,6,99,México,97,97
432,2021-12-13,1a18dc,1,4,16,2,16,16,52,2,...,99,1,2,2,97,7,99,México,97,99
1074,2021-12-13,17c34a,1,4,16,2,16,16,52,2,...,99,1,2,2,97,7,99,México,97,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12041162,2021-12-13,75ada1,1,12,16,1,16,16,52,1,...,2,2,97,1,2,7,99,México,97,97
12041214,2021-12-13,9a23e9,1,12,16,1,16,16,52,1,...,2,2,97,1,2,7,99,México,97,97
12041706,2021-12-13,93faa2,1,12,16,1,12,16,52,1,...,2,2,97,1,2,7,99,México,97,97
12041780,2021-12-13,534bf7,1,12,16,1,16,16,52,1,...,2,2,97,1,2,7,99,México,97,97
12042007,2021-12-13,74052a,1,12,16,1,16,16,52,1,...,2,2,97,1,2,7,99,México,97,97

In [99]:
#columnas = ['FECHA_ACTUALIZACION','ID_REGISTRO','ORIGEN','ENTIDAD_RES','MUNICIPIO_RES','INTUBADO'
#,'NEUMONIA','EDAD','DIABETES','ASMA','HIPERTENSION','OBESIDAD','TABAQUISMO','TOMA_MUESTRA_LAB','RESULTADO_ANTIGENO']

In [100]:
Morelia.shape

(32079, 40)

In [101]:
#Morelia.loc[:,['FECHA_ACTUALIZACION','ID_REGISTRO','ORIGEN','ENTIDAD_RES','MUNICIPIO_RES','INTUBADO'
#,'NEUMONIA','EDAD','DIABETES','ASMA','HIPERTENSION','OBESIDAD','TABAQUISMO','TOMA_MUESTRA_LAB','RESULTADO_ANTIGENO']]

In [110]:
Morelia = Morelia.loc[:,['FECHA_ACTUALIZACION','ID_REGISTRO'
,'ORIGEN','SECTOR','ENTIDAD_RES','SEXO','MUNICIPIO_RES','INTUBADO','FECHA_DEF'
,'EDAD',"TIPO_PACIENTE","FECHA_INGRESO","FECHA_SINTOMAS","NEUMONIA","EMBARAZO","DIABETES"
,"EPOC","ASMA","INMUSUPR","HIPERTENSION","OTRA_COM","CARDIOVASCULAR","OBESIDAD","RENAL_CRONICA","TABAQUISMO"
,"TOMA_MUESTRA_ANTIGENO","RESULTADO_ANTIGENO",'TOMA_MUESTRA_LAB','CLASIFICACION_FINAL' ,'RESULTADO_LAB','UCI']]

In [111]:
'''          
,"TIPO_PACIENTE"
,"FECHA_INGRESO"
,"FECHA_SINTOMAS"
,"FECHA_DEF"
,"INTUBADO"
,"NEUMONIA"
,"EDAD"
,"EMBARAZO"
,"DIABETES"
,"EPOC"
,"ASMA"
,"INMUSUPR"
,"HIPERTENSION"
,"OTRA_COM"
,"CARDIOVASCULAR"
,"OBESIDAD"
,"RENAL_CRONICA"
,"TABAQUISMO"
,"RESULTADO_LAB"
,"TOMA_MUESTRA_ANTIGENO"
,"RESULTADO_ANTIGENO"
'''

'          \n,"TIPO_PACIENTE"\n,"FECHA_INGRESO"\n,"FECHA_SINTOMAS"\n,"FECHA_DEF"\n,"INTUBADO"\n,"NEUMONIA"\n,"EDAD"\n,"EMBARAZO"\n,"DIABETES"\n,"EPOC"\n,"ASMA"\n,"INMUSUPR"\n,"HIPERTENSION"\n,"OTRA_COM"\n,"CARDIOVASCULAR"\n,"OBESIDAD"\n,"RENAL_CRONICA"\n,"TABAQUISMO"\n,"RESULTADO_LAB"\n,"TOMA_MUESTRA_ANTIGENO"\n,"RESULTADO_ANTIGENO"\n'

In [112]:
Morelia.head()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,EDAD,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
382,2021-12-13,1d50dc,1,4,16,1,52,99,2020-01-24,68,...,2,2,2,2,2,97,1,7,2,99
401,2021-12-13,1e005b,1,4,16,1,52,97,9999-99-99,76,...,2,2,2,2,2,97,2,6,97,97
429,2021-12-13,054314,1,4,16,2,52,97,9999-99-99,25,...,2,2,2,2,2,97,2,6,97,97
432,2021-12-13,1a18dc,1,4,16,2,52,99,9999-99-99,76,...,2,2,2,2,2,97,1,7,2,99
1074,2021-12-13,17c34a,1,4,16,2,52,99,9999-99-99,1,...,2,2,2,2,2,97,1,7,2,99

In [113]:
A =Morelia['FECHA_ACTUALIZACION'].unique()
a = Morelia.iloc[1,8]
b = '9999-99-99'
print(a==b)

True

In [114]:
Morelia.FECHA_DEF

382         2020-01-24
401         9999-99-99
429         9999-99-99
432         9999-99-99
1074        9999-99-99
               ...
12041162    9999-99-99
12041214    9999-99-99
12041706    9999-99-99
12041780    9999-99-99
12042007    9999-99-99
Name: FECHA_DEF, Length: 32079, dtype: object

In [115]:
Morelia_Muertos = Morelia[(Morelia.FECHA_DEF != '9999-99-99') & ((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3))]
Morelia_MuertosN = Morelia_Muertos.shape[0]
Morelia_Muertos

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,EDAD,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
42078,2021-12-13,19fea6,1,12,16,2,52,1,2020-03-26,72,...,2,1,2,2,2,97,1,3,1,1
42270,2021-12-13,0863b9,1,12,16,1,52,2,2020-04-13,63,...,2,1,2,2,2,97,1,3,1,2
49136,2021-12-13,129268,1,12,16,2,52,2,2020-04-25,69,...,2,2,2,2,2,97,1,3,1,2
56684,2021-12-13,020054,1,4,16,2,52,2,2020-04-26,74,...,2,1,2,2,2,97,1,3,1,2
67319,2021-12-13,19076f,1,4,16,2,52,2,2020-04-19,71,...,2,2,2,1,2,97,1,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10803757,2021-12-13,a42064,1,12,16,2,52,2,2021-10-08,69,...,2,2,2,2,1,1,1,3,1,2
10918691,2021-12-13,d3d91e,1,4,16,2,52,2,2021-10-15,51,...,2,1,2,2,1,1,1,3,1,2
10976848,2021-12-13,d7ba23,1,4,16,2,52,2,2021-10-15,58,...,2,2,2,1,1,1,1,3,1,2
11447815,2021-12-13,85b16e,1,12,16,1,52,2,2021-11-12,45,...,2,2,2,2,1,1,1,3,1,2
11678664,2021-12-13,975191,1,4,16,2,52,2,2021-12-05,72,...,2,2,2,2,1,1,1,3,1,2

In [116]:
Morelia_infectados = Morelia[((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3))]
Morelia_infectados_N = Morelia_infectados.shape[0]
Morelia_infectados_N
Morelia_infectados

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,EDAD,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
31176,2021-12-13,18ef9f,1,4,16,1,52,97,9999-99-99,20,...,2,2,2,2,2,97,1,3,1,97
42078,2021-12-13,19fea6,1,12,16,2,52,1,2020-03-26,72,...,2,1,2,2,2,97,1,3,1,1
42270,2021-12-13,0863b9,1,12,16,1,52,2,2020-04-13,63,...,2,1,2,2,2,97,1,3,1,2
42371,2021-12-13,1c613d,2,12,16,1,52,97,9999-99-99,29,...,2,2,2,2,2,97,1,3,1,97
42382,2021-12-13,0d8077,2,12,16,2,52,97,9999-99-99,31,...,2,2,2,2,2,97,1,3,1,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11945618,2021-12-13,9330e9,1,4,16,2,52,97,9999-99-99,24,...,2,2,2,2,1,1,1,3,1,97
11945697,2021-12-13,984fc9,1,4,16,1,52,97,9999-99-99,26,...,2,2,2,2,1,2,1,3,1,97
11977561,2021-12-13,c89829,2,12,16,2,52,97,9999-99-99,39,...,2,2,2,2,1,1,1,3,1,97
11977949,2021-12-13,83bbe0,2,12,16,2,52,97,9999-99-99,58,...,2,2,2,2,1,1,1,3,1,97
11984735,2021-12-13,910b87,2,6,16,2,52,97,9999-99-99,43,...,2,1,2,2,1,1,2,3,97,97

In [117]:
Morelia.INTUBADO

382         99
401         97
429         97
432         99
1074        99
            ..
12041162    97
12041214    97
12041706    97
12041780    97
12042007    97
Name: INTUBADO, Length: 32079, dtype: int64

In [118]:
Morelia_infectadosG_vivos = Morelia[(Morelia.FECHA_DEF == '9999-99-99') & ((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3)) & (Morelia.INTUBADO == 1)]

Morelia_infectadosG_vivos_N = Morelia_infectadosG_vivos.shape[0]

Morelia_infectadosG_vivos

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,EDAD,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
223860,2021-12-13,1a50c9,2,9,16,1,52,1,9999-99-99,55,...,2,2,2,2,2,97,1,3,1,1
233500,2021-12-13,0a8210,2,9,16,2,52,1,9999-99-99,65,...,1,2,2,2,2,97,1,3,1,2
328407,2021-12-13,0594b3,2,4,16,2,52,1,9999-99-99,38,...,2,2,2,2,2,97,1,3,1,2
423169,2021-12-13,0635fc,1,4,16,2,52,1,9999-99-99,31,...,2,2,2,2,2,97,1,3,1,2
437110,2021-12-13,12de0e,1,4,16,2,52,1,9999-99-99,67,...,2,2,2,2,2,97,1,3,1,2
498284,2021-12-13,1936e4,1,4,16,2,52,1,9999-99-99,41,...,2,2,2,2,2,97,1,3,1,2
508925,2021-12-13,1462bc,1,4,16,2,52,1,9999-99-99,38,...,2,1,2,2,2,97,1,3,1,2
645907,2021-12-13,14efdd,1,4,16,2,52,1,9999-99-99,64,...,2,2,2,1,2,97,1,3,1,2
705583,2021-12-13,17df54,1,4,16,2,52,1,9999-99-99,53,...,2,2,2,2,2,97,1,3,1,2
990125,2021-12-13,0477cc,1,4,16,2,52,1,9999-99-99,55,...,2,2,2,2,2,97,1,3,1,2
1008342,2021-12-13,141f18,1,4,16,2,52,1,9999-99-99,52,...,2,2,2,2,2,97,1,3,1,2
3411562,2021-12-13,38e03e,2,11,16,2,52,1,9999-99-99,79,...,1,2,2,2,2,97,1,3,1,2
4711933,2021-12-13,68a2ab,2,6,16,1,52,1,9999-99-99,56,...,2,1,2,2,2,97,1,3,1,2
6419433,2021-12-13,683cba,1,12,16,2,52,1,9999-99-99,50,...,1,1,2,2,2,97,1,3,1,2
8810689,2021-12-13,663e37,1,12,16,2,52,1,9999-99-99,62,...,2,2,2,2,2,97,1,3,1,1
9869524,2021-12-13,68615c,1,12,16,1,52,1,9999-99-99,17,...,2,1,2,2,1,2,1,3,1,2
10070245,2021-12-13,8d7522,2,9,16,1,52,1,9999-99-99,47,...,98,98,98,98,1,2,2,1,97,1

In [119]:
Morelia_infectados_grave = Morelia[((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3)) & (Morelia.INTUBADO == 1)]

Morelia_infectados_grave_N = Morelia_infectados_grave.shape[0]

Morelia_infectados_grave

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,EDAD,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
42078,2021-12-13,19fea6,1,12,16,2,52,1,2020-03-26,72,...,2,1,2,2,2,97,1,3,1,1
75337,2021-12-13,0dde42,2,6,16,2,52,1,2020-04-25,43,...,2,1,2,2,2,97,1,3,1,1
100967,2021-12-13,12a794,1,4,16,2,52,1,2020-05-05,75,...,2,2,2,2,2,97,1,3,1,2
115506,2021-12-13,1b09dc,1,4,16,2,52,1,2020-04-28,71,...,2,2,2,2,2,97,1,3,1,2
135807,2021-12-13,0fdf7d,1,12,16,2,52,1,2020-05-01,52,...,2,2,2,2,2,97,1,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9869524,2021-12-13,68615c,1,12,16,1,52,1,9999-99-99,17,...,2,1,2,2,1,2,1,3,1,2
10014525,2021-12-13,c55a52,1,4,16,1,52,1,2021-09-09,64,...,2,2,2,2,1,1,1,3,1,2
10070245,2021-12-13,8d7522,2,9,16,1,52,1,9999-99-99,47,...,98,98,98,98,1,2,2,1,97,1
10206098,2021-12-13,ba0a89,2,6,16,1,52,1,2021-10-01,79,...,2,1,2,2,1,1,2,3,97,2
10559954,2021-12-13,4ee4cb,1,4,16,2,52,1,2021-10-07,72,...,2,2,2,2,1,1,1,3,1,2

In [120]:
Morelia_infectadosG_Muertos = Morelia[(Morelia.FECHA_DEF != '9999-99-99') & ((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3)) & (Morelia.INTUBADO == 1)]
Morelia_infectadosG_MuertosN = Morelia_infectadosG_Muertos.shape[0]

# ((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3))
Morelia_infectadosG_Muertos

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,EDAD,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
42078,2021-12-13,19fea6,1,12,16,2,52,1,2020-03-26,72,...,2,1,2,2,2,97,1,3,1,1
75337,2021-12-13,0dde42,2,6,16,2,52,1,2020-04-25,43,...,2,1,2,2,2,97,1,3,1,1
100967,2021-12-13,12a794,1,4,16,2,52,1,2020-05-05,75,...,2,2,2,2,2,97,1,3,1,2
115506,2021-12-13,1b09dc,1,4,16,2,52,1,2020-04-28,71,...,2,2,2,2,2,97,1,3,1,2
135807,2021-12-13,0fdf7d,1,12,16,2,52,1,2020-05-01,52,...,2,2,2,2,2,97,1,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9734475,2021-12-13,488b3f,1,12,16,1,52,1,2021-09-10,64,...,2,1,2,2,1,1,1,3,1,2
9795703,2021-12-13,d1b72c,2,4,16,2,52,1,2021-09-06,76,...,2,2,2,1,1,1,1,3,1,2
10014525,2021-12-13,c55a52,1,4,16,1,52,1,2021-09-09,64,...,2,2,2,2,1,1,1,3,1,2
10206098,2021-12-13,ba0a89,2,6,16,1,52,1,2021-10-01,79,...,2,1,2,2,1,1,2,3,97,2
10559954,2021-12-13,4ee4cb,1,4,16,2,52,1,2021-10-07,72,...,2,2,2,2,1,1,1,3,1,2

In [121]:
Morelia.RESULTADO_LAB

382          2
401         97
429         97
432          2
1074         2
            ..
12041162    97
12041214    97
12041706    97
12041780    97
12042007    97
Name: RESULTADO_LAB, Length: 32079, dtype: int64

In [122]:
Morelia_infectadosG = Morelia[ (((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3)) )
                                    & (Morelia.INTUBADO == 1)]


Morelia_infectadosGN = Morelia_infectadosG.shape[0]
Morelia_infectadosG

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,EDAD,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
42078,2021-12-13,19fea6,1,12,16,2,52,1,2020-03-26,72,...,2,1,2,2,2,97,1,3,1,1
75337,2021-12-13,0dde42,2,6,16,2,52,1,2020-04-25,43,...,2,1,2,2,2,97,1,3,1,1
100967,2021-12-13,12a794,1,4,16,2,52,1,2020-05-05,75,...,2,2,2,2,2,97,1,3,1,2
115506,2021-12-13,1b09dc,1,4,16,2,52,1,2020-04-28,71,...,2,2,2,2,2,97,1,3,1,2
135807,2021-12-13,0fdf7d,1,12,16,2,52,1,2020-05-01,52,...,2,2,2,2,2,97,1,3,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9869524,2021-12-13,68615c,1,12,16,1,52,1,9999-99-99,17,...,2,1,2,2,1,2,1,3,1,2
10014525,2021-12-13,c55a52,1,4,16,1,52,1,2021-09-09,64,...,2,2,2,2,1,1,1,3,1,2
10070245,2021-12-13,8d7522,2,9,16,1,52,1,9999-99-99,47,...,98,98,98,98,1,2,2,1,97,1
10206098,2021-12-13,ba0a89,2,6,16,1,52,1,2021-10-01,79,...,2,1,2,2,1,1,2,3,97,2
10559954,2021-12-13,4ee4cb,1,4,16,2,52,1,2021-10-07,72,...,2,2,2,2,1,1,1,3,1,2

In [123]:
Morelia_negativos =  Morelia[ (Morelia.RESULTADO_LAB == 2 )]
Morelia_negativosN = Morelia_negativos.shape[0]
Morelia_negativos

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,EDAD,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
382,2021-12-13,1d50dc,1,4,16,1,52,99,2020-01-24,68,...,2,2,2,2,2,97,1,7,2,99
432,2021-12-13,1a18dc,1,4,16,2,52,99,9999-99-99,76,...,2,2,2,2,2,97,1,7,2,99
1074,2021-12-13,17c34a,1,4,16,2,52,99,9999-99-99,1,...,2,2,2,2,2,97,1,7,2,99
1075,2021-12-13,1b3a24,1,4,16,1,52,99,9999-99-99,77,...,2,2,2,2,2,97,1,7,2,99
1362,2021-12-13,0f362b,1,4,16,1,52,99,9999-99-99,5,...,2,2,2,2,2,97,1,7,2,99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11928470,2021-12-13,9870b7,1,4,16,2,52,2,9999-99-99,69,...,2,2,2,2,1,2,1,7,2,2
11931874,2021-12-13,5d2d7f,2,12,16,2,52,97,9999-99-99,38,...,2,2,2,2,1,2,1,7,2,97
11935331,2021-12-13,77f447,1,12,16,2,52,97,9999-99-99,16,...,2,2,2,2,1,2,1,7,2,97
11975860,2021-12-13,599297,2,12,16,2,52,97,9999-99-99,47,...,2,2,2,2,1,2,1,7,2,97
11993032,2021-12-13,caa175,1,4,16,1,52,2,9999-99-99,77,...,2,2,2,2,1,2,1,7,2,2

In [124]:
datos_finales = [Morelia_MuertosN
,Morelia_infectados_N
,Morelia_infectadosG_vivos_N 
,Morelia_infectadosG_MuertosN
,Morelia_infectados_grave_N
,Morelia.shape[0]];datos_finales
#,Morelia_MuertosN+Morelia_infectados_N+Morelia_infectadosG_vivos_N +Morelia_infectadosG_MuertosN];datos_f

[668, 11890, 17, 136, 153, 32079]

In [125]:
Morelia.NEUMONIA== '2'

382         False
401         False
429         False
432         False
1074        False
            ...
12041162    False
12041214    False
12041706    False
12041780    False
12042007    False
Name: NEUMONIA, Length: 32079, dtype: bool

In [132]:
Morelia_muertos_sinEnfermedades = Morelia[((Morelia.FECHA_DEF != '9999-99-99') &
                                   ((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3)) &
                                  (Morelia.NEUMONIA== 2) & (Morelia.DIABETES == 2) & (Morelia.CARDIOVASCULAR ==2) & (Morelia.OBESIDAD ==2) & (Morelia.RENAL_CRONICA == 2) 
                                    & (Morelia.TABAQUISMO == 2) & (Morelia.EPOC == 2) & (Morelia.ASMA == 2) & (Morelia.INMUSUPR == 2) & (Morelia.HIPERTENSION == 2)) ]
Morelia_muertos_sinEnfermedades

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,EDAD,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
97524,2021-12-13,182677,1,12,16,2,52,2,2020-04-23,54,...,2,2,2,2,2,97,1,3,1,2
139876,2021-12-13,034d67,1,4,16,2,52,2,2020-04-28,38,...,2,2,2,2,2,97,1,3,1,2
186963,2021-12-13,0e1f56,1,4,16,2,52,2,2020-05-31,57,...,2,2,2,2,2,97,1,3,1,2
222558,2021-12-13,1cc6bb,1,4,16,2,52,2,2020-05-25,53,...,2,2,2,2,2,97,1,3,1,2
505158,2021-12-13,09e1a6,1,4,16,2,52,1,2020-06-15,72,...,2,2,2,2,2,97,1,3,1,2
847707,2021-12-13,1df79b,1,4,16,1,52,2,2020-07-11,39,...,2,2,2,2,2,97,1,3,1,2
849150,2021-12-13,026fdd,1,4,16,2,52,2,2020-07-10,66,...,2,2,2,2,2,97,2,2,97,2
962682,2021-12-13,13b18a,1,4,16,2,52,2,2020-08-01,26,...,2,2,2,2,2,97,1,3,1,2
1041060,2021-12-13,193d35,1,4,16,2,52,2,2020-07-21,69,...,2,2,2,2,2,97,2,2,97,2
1527818,2021-12-13,006496,1,4,16,2,52,2,2020-08-28,60,...,2,2,2,2,2,97,2,2,97,2
1639742,2021-12-13,2a66ea,1,4,16,2,52,2,2020-09-29,54,...,2,2,2,2,2,97,1,2,4,2
1876663,2021-12-13,236262,1,4,16,1,52,99,2020-09-25,62,...,2,2,2,2,2,97,1,3,1,99
1900288,2021-12-13,302f4e,1,4,16,2,52,2,2020-10-03,56,...,2,2,2,2,2,97,1,2,4,2
1904092,2021-12-13,3c21c6,1,4,16,2,52,2,2020-09-26,53,...,2,2,2,2,2,97,1,2,4,2
4210481,2021-12-13,a274a2,1,4,16,2,52,2,2021-01-23,69,...,2,2,2,2,1,1,1,3,1,2
8480779,2021-12-13,999d32,1,4,16,2,52,2,2021-09-20,32,...,2,2,2,2,1,1,2,3,97,2
8935867,2021-12-13,88c276,1,4,16,2,52,2,2021-08-21,55,...,2,2,2,2,1,1,1,3,1,2
9339212,2021-12-13,a377cf,1,4,16,2,52,2,2021-08-28,65,...,2,2,2,2,1,2,1,3,1,2
9452073,2021-12-13,9b9215,2,6,16,2,52,2,2021-08-26,72,...,2,2,2,2,2,97,1,3,1,2
9514797,2021-12-13,8ea252,2,6,16,2,52,2,2021-08-25,59,...,2,2,2,2,2,97,1,3,1,2
10205392,2021-12-13,bceddd,2,6,16,2,52,2,2021-09-26,69,...,2,2,2,2,1,2,1,3,1,2

In [133]:
Morelia_infectados_sinEnfermedades = Morelia[(
                                   ((Morelia.CLASIFICACION_FINAL ==1) | (Morelia.CLASIFICACION_FINAL ==2) | (Morelia.CLASIFICACION_FINAL ==3)) &
                                  (Morelia.NEUMONIA== 2) & (Morelia.DIABETES == 2) & (Morelia.CARDIOVASCULAR ==2) & (Morelia.OBESIDAD ==2) & (Morelia.RENAL_CRONICA == 2) 
                                    & (Morelia.TABAQUISMO == 2) & (Morelia.EPOC == 2) & (Morelia.ASMA == 2) & (Morelia.INMUSUPR == 2) & (Morelia.HIPERTENSION == 2)) ]
Morelia_infectados_sinEnfermedades

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_RES,SEXO,MUNICIPIO_RES,INTUBADO,FECHA_DEF,EDAD,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,TOMA_MUESTRA_ANTIGENO,RESULTADO_ANTIGENO,TOMA_MUESTRA_LAB,CLASIFICACION_FINAL,RESULTADO_LAB,UCI
31176,2021-12-13,18ef9f,1,4,16,1,52,97,9999-99-99,20,...,2,2,2,2,2,97,1,3,1,97
42382,2021-12-13,0d8077,2,12,16,2,52,97,9999-99-99,31,...,2,2,2,2,2,97,1,3,1,97
56409,2021-12-13,1caf5d,1,4,16,2,52,2,9999-99-99,33,...,2,2,2,2,2,97,1,3,1,2
66965,2021-12-13,0701e4,1,4,16,2,52,2,9999-99-99,55,...,2,2,2,2,2,97,1,3,1,2
68825,2021-12-13,1d3b40,1,4,16,2,52,97,9999-99-99,49,...,2,2,2,2,2,97,1,3,1,97
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11933810,2021-12-13,77c996,2,12,16,1,52,97,9999-99-99,58,...,2,2,2,2,1,1,1,3,3,97
11945618,2021-12-13,9330e9,1,4,16,2,52,97,9999-99-99,24,...,2,2,2,2,1,1,1,3,1,97
11945697,2021-12-13,984fc9,1,4,16,1,52,97,9999-99-99,26,...,2,2,2,2,1,2,1,3,1,97
11977561,2021-12-13,c89829,2,12,16,2,52,97,9999-99-99,39,...,2,2,2,2,1,1,1,3,1,97
11977949,2021-12-13,83bbe0,2,12,16,2,52,97,9999-99-99,58,...,2,2,2,2,1,1,1,3,1,97

In [127]:
rows = ['Muertos','Infectados','Infectados graves vivos','Infectados graves muertos','Infectados graves','Total']
col = ['Casos']
df = pd.DataFrame(data = datos_finales, columns = col, index = rows)
df

                           Casos
Muertos                      668
Infectados                 11890
Infectados graves vivos       17
Infectados graves muertos    136
Infectados graves            153
Total                      32079

In [128]:
#total = Morelia_MuertosN+Morelia_infectados_N+Morelia_infectadosG_vivos_N +Morelia_infectadosG_MuertosN

total = Morelia.shape[0]
porce = [(Morelia_MuertosN*100)/total,(Morelia_infectados_N*100)/total,(Morelia_infectadosG_vivos_N*100)/total,(Morelia_infectadosG_MuertosN*100)/total,(Morelia_infectados_grave_N*100)/total,100]
porce

[2.0823591757847812,
 37.06474640730696,
 0.052994170641229466,
 0.4239533651298357,
 0.4769475357710652,
 100]

In [129]:
df['Porcentaje'] = porce
df

                           Casos  Porcentaje
Muertos                      668    2.082359
Infectados                 11890   37.064746
Infectados graves vivos       17    0.052994
Infectados graves muertos    136    0.423953
Infectados graves            153    0.476948
Total                      32079  100.000000

In [138]:
pM = 136*100/153
pig = 153*100/11890 
pmse = 21*100/668
pise = 7952*100/11890

In [107]:
pM

88.88888888888889

In [108]:
pig

1.2867956265769553

In [136]:
pmse

3.143712574850299

In [139]:
pise

66.87973086627419

In [141]:
df1 = pd.DataFrame(data = [pM,pig,pmse,pise], index = ('Infectados graves muertos','Infectados graves','Muertos sin enfermedades','Infectados sin enfermedades'), columns = ['Porcentaje'] )
df1

                             Porcentaje
Infectados graves muertos     88.888889
Infectados graves              1.286796
Muertos sin enfermedades       3.143713
Infectados sin enfermedades   66.879731